##
# Jekyll
# https://jekyllrb.com/docs/configuration/
##

## Jekyll / Configuration
permalink: /posts/:year/:title/
exclude:
  - LICENSE.txt
  - README.md
timezone: Europe/London
# Used by 'jekyll build'. Ignored by 'jekyll serve'.
url: https://timotijhof.net

## Jekyll / Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

## Jekyll / Posts
## https://jekyllrb.com/docs/posts/#post-excerpts
excerpt_separator: <!--more-->

## Jekyll / Sass
## https://jekyllrb.com/docs/assets/#sassscss
sass:
  style: compressed
  sourcemap: never

##
# Theme configuration
##

title: Timo Tijhof
description: >
  Software updates, inner musings, and (hopefully) educational findings.

plainwhite:
  # Title in sidebar
  name: Timo Tijhof
  # Caption in sidebar
  tagline: Principal Engineer, Wikimedia Foundation.
  date_format: "%e %b %Y"
  # Excerpts on Home and Tag pages
  show_excerpts: true
  # Tag filter for Home page
  exclude_tag: wiki-tools
  social_links:
    github:  Krinkle
    twitter: TimoTijhof
  stat_url: https://stats.timotijhof.net/matomo.php?idsite=8&rec=1

defaults:
  - scope:
      path: ""
    values:
      author: "Timo Tijhof"
