##
# Jekyll
# https://jekyllrb.com/docs/configuration/
##

## Jekyll / Configuration
permalink: /posts/:year/:title/
include:
  - .htaccess
  - .well-known
exclude:
  - LICENSE.txt
  - README.md
timezone: Europe/London
# Used by 'jekyll build'. Ignored by 'jekyll serve'.
url: https://timotijhof.net

## Jekyll / Plugins
plugins:
  - jekyll-redirect-from
  #  https://github.com/benbalter/jekyll-relative-links
  - jekyll-relative-links

## Jekyll / Posts
## https://jekyllrb.com/docs/posts/#post-excerpts
excerpt_separator: <!--more-->

## Jekyll / Sass
## https://jekyllrb.com/docs/assets/#sassscss
sass:
  style: compressed
  sourcemap: never

## Jekyll / Markdown
## https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown

##
# Unofficial site vars that various plugins consider.
##
author: Timo Tijhof

##
# Theme configuration
##

title: Timo Tijhof
description: >
  Inner musings, and (hopefully) educational findings.

plainwhite:
  # Title in sidebar
  name: Timo Tijhof
  # Caption in sidebar
  tagline: Principal Engineer, Wikimedia Foundation.
  # Date format in by lines
  date_format: "%-e %b %Y"
  # Excerpts on Home and Tag pages
  show_excerpts: true
  # Tag filter for Home page
  exclude_tags:
    - wiki-tools
    - english-language
  social_links:
    github:  Krinkle
    mastodon:
      user: krinkle
      instance: mastodon.technology
    twitter: TimoTijhof
  matomo:
    url: https://stats.timotijhof.net
    idsite: 8

defaults:
  - scope:
      path: ""
    values:
      author: "Timo Tijhof"
