##
# Jekyll
# https://jekyllrb.com/docs/configuration/
##

## Jekyll / Configuration
permalink: /posts/:title/
exclude:
  - LICENSE.txt
  - README.md
timezone: Europe/London

## Jekyll / Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

sass:
  style: compressed

##
# Theme configuration
##

title: Timo Tijhof
description: >
  Software updates, inner musings, and (hopefully) educational findings.
# Excerpts on the homepage

plainwhite:
  # Title in sidebar
  name: Timo Tijhof
  # Caption in sidebar
  tagline: Principal Engineer, Wikimedia Foundation.
  date_format: "%b %-d, %Y"
  # Except on Home and Tag pages
  show_excerpts: true
  social_links:
    github:  Krinkle
    twitter: TimoTijhof

# ## Theme configuration / License
# licenses:
#   CC-BY-4.0:
#     name: Creative Commons
#     url: https://creativecommons.org/licenses/by/4.0/
#     image: https://i.creativecommons.org/l/by/4.0/88x31.png
#   CC-BY-ND-4.0:
#     name: Creative Commons
#     url: https://creativecommons.org/licenses/by-nd/4.0/
#     image: https://i.creativecommons.org/l/by-nd/4.0/88x31.png
